enum Actions {
  // action types
  ADD_BODY_CLASSNAME = "ADD_BODY_CLASSNAME",
  REMOVE_BODY_CLASSNAME = "REMOVE_BODY_CLASSNAME",
  ADD_BODY_ATTRIBUTE = "ADD_BODY_ATTRIBUTE",
  REMOVE_BODY_ATTRIBUTE = "REMOVE_BODY_ATTRIBUTE",
  ADD_CLASSNAME = "ADD_CLASSNAME",
  VERIFY_AUTH = "VERIFY_AUTH",
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  REGISTER = "REGISTER",
  UPDATE_USER = "UPDATE_USER",
  FORGOT_PASSWORD = "FORGOT_PASSWORD",
  SET_BREADCRUMB_ACTION = "SET_BREADCRUMB_ACTION",

  // ProfileModule
  UPDATE_PERSONAL_INFO = "UPDATE_PERSONAL_INFO",
  UPDATE_ACCOUNT_INFO = "UPDATE_ACCOUNT_INFO",
  GET_PROFILE = "GET_PROFILE",

  // EnumsAndConstantsModule
  GET_ENUMS_AND_CONSTANTS = "GET_ENUMS_AND_CONSTANTS",

  // SocketModule
  CONNECT_SOCKET = "CONNECT_SOCKET",
  DISCONNECT_SOCKET = "DISCONNECT_SOCKET",

  // NotificationsModule
  CONNECT_PRIVATE_CHANNEL = "CONNECT_PRIVATE_CHANNEL",
  GET_NOTIFICATIONS = "GET_NOTIFICATIONS",
}

enum Mutations {
  // mutation types
  SET_CLASSNAME_BY_POSITION = "SET_CLASSNAME_BY_POSITION",
  PURGE_AUTH = "PURGE_AUTH",
  SET_AUTH = "SET_AUTH",
  SET_USER = "SET_USER",
  SET_PASSWORD = "SET_PASSWORD",
  SET_ERROR = "SET_ERROR",
  SET_BREADCRUMB_MUTATION = "SET_BREADCRUMB_MUTATION",
  SET_LAYOUT_CONFIG = "SET_LAYOUT_CONFIG",
  RESET_LAYOUT_CONFIG = "RESET_LAYOUT_CONFIG",
  OVERRIDE_LAYOUT_CONFIG = "OVERRIDE_LAYOUT_CONFIG",
  OVERRIDE_PAGE_LAYOUT_CONFIG = "OVERRIDE_PAGE_LAYOUT_CONFIG",

  // ProfileModule
  SET_PERSONAL_INFO = "SET_PERSONAL_INFO",
  SET_ACCOUNT_INFO = "SET_ACCOUNT_INFO",
  SET_PROFILE = "SET_PROFILE",

  // EnumsAndConstantsModule
  SET_ENUMS_AND_CONSTANTS = "SET_ENUMS_AND_CONSTANTS",

  // SocketModule,

  // NotificationsModule
  ADD_NOTIFICATION = "ADD_NOTIFICATION",
  SET_NOTIFICATION_AS_READ = "SET_NOTIFICATION_AS_READ",
  SET_NOTIFICATIONS = "SET_NOTIFICATIONS",
}

export { Actions, Mutations };
